import { Alert, Box, Button, Divider, Paper, Stack, TextField, Typography } from '@mui/material';
import { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { request } from '../api.js';

type Unit={id:string;serialNumber:string;uid:string;status:'enabled'|'disabled'|'unavailable';assignedUser?:{id:string;email:string;firstName?:string;lastName?:string}};
type Person={id:string;email:string;firstName?:string;lastName?:string;lifecycle:string;balance?:number};
const label=(p:Pick<Person,'email'|'firstName'|'lastName'>)=>`${[p.firstName,p.lastName].filter(Boolean).join(' ')||p.email} · ${p.email}`;
export function AdminConsole(){const location=useLocation(),nav=useNavigate();const section=location.pathname.split('/')[2]||'psiu';return <Stack direction={{xs:'column',md:'row'}} spacing={3}><Paper component="nav" sx={{p:1,minWidth:220,height:'fit-content'}}><Typography variant="h6" sx={{p:1}}>Administration</Typography>{[['psiu','PSIU Management'],['users','User Management'],['credits','Credits'],['samples','Samples']].map(([id,text])=><Button key={id} fullWidth sx={{justifyContent:'flex-start'}} variant={section===id?'contained':'text'} onClick={()=>nav(`/admin/${id}`)}>{text}</Button>)}</Paper><Box sx={{flex:1,minWidth:0}}>{section==='psiu'?<Psiu/>:section==='users'?<Users/>:section==='credits'?<Credits/>:<Samples/>}</Box></Stack>}
function Psiu(){const[units,setUnits]=useState<Unit[]>([]),[people,setPeople]=useState<Person[]>([]),[query,setQuery]=useState(''),[serial,setSerial]=useState(''),[uid,setUid]=useState(''),[message,setMessage]=useState('');const load=()=>request<Unit[]>('/v1/admin/psiu-units').then(setUnits).catch(e=>setMessage(e.message));useEffect(()=>{void load()},[]);useEffect(()=>{if(query.trim().length<2){setPeople([]);return}const t=setTimeout(()=>void request<Person[]>(`/v1/admin/users/typeahead?q=${encodeURIComponent(query)}`).then(setPeople).catch(e=>setMessage(e.message)),250);return()=>clearTimeout(t)},[query]);const action=async(path:string,body?:unknown)=>{try{await request(path,{method:'POST',body:body?JSON.stringify(body):undefined});await load();setQuery('');setPeople([])}catch(e){setMessage(e instanceof Error?e.message:'Action failed')}};return <Stack spacing={2}><Typography variant="h4">PSIU Management</Typography>{message&&<Alert severity="error">{message}</Alert>}<Paper sx={{p:2}}><Stack direction={{xs:'column',sm:'row'}} spacing={1}><TextField label="Serial number" value={serial} onChange={e=>setSerial(e.target.value)}/><TextField label="Firmware UID" value={uid} onChange={e=>setUid(e.target.value)}/><Button onClick={()=>void action('/v1/admin/psiu-units',{serialNumber:serial,uid}).then(()=>{setSerial('');setUid('')})}>Add PSIU</Button></Stack></Paper>{units.map(u=><Paper key={u.id} sx={{p:2,borderLeft:6,borderColor:u.status!=='enabled'?'error.main':u.assignedUser?'success.main':'transparent'}}><Stack spacing={1}><Typography>{u.serialNumber} · {u.uid} · {u.status} {u.assignedUser&&`· ${label(u.assignedUser)}`}</Typography>{u.status!=='unavailable'&&<Stack direction="row" spacing={1}><Button size="small" onClick={()=>void action(`/v1/admin/psiu-units/${u.id}/${u.status==='enabled'?'disable':'enable'}`)}>{u.status==='enabled'?'Disable':'Enable'}</Button><Button size="small" onClick={()=>void action(`/v1/admin/psiu-units/${u.id}/unavailable`)}>Mark unavailable</Button>{u.assignedUser?<Button size="small" onClick={()=>void action(`/v1/admin/psiu-units/${u.id}/deassign`)}>Deassign</Button>:<><TextField size="small" label="Assign user" value={query} onChange={e=>setQuery(e.target.value)}/>{people.map(p=><Button key={p.id} size="small" onClick={()=>void action(`/v1/admin/psiu-units/${u.id}/assign`,{customerId:p.id})}>{label(p)}</Button>)}</>}</Stack>}<Button size="small" color="error" onClick={()=>void request(`/v1/admin/psiu-units/${u.id}`,{method:'DELETE'}).then(load).catch(e=>setMessage(e.message))}>Hard delete</Button></Stack></Paper>)}</Stack>}
function Users(){const[users,setUsers]=useState<Person[]>([]),[q,setQ]=useState(''),[message,setMessage]=useState('');const load=()=>request<{items:Person[]}|Person[]>(`/v1/admin/users?q=${encodeURIComponent(q)}`).then(x=>setUsers(Array.isArray(x)?x:x.items)).catch(e=>setMessage(e.message));useEffect(()=>{void load()},[]);return <Stack spacing={2}><Typography variant="h4">User Management</Typography><TextField label="Search name, email, or PSIU serial" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load()}}/>{message&&<Alert severity="error">{message}</Alert>}{users.map(u=><Paper key={u.id} sx={{p:2}}><Typography>{label(u)} · {u.lifecycle} · {u.balance??0} credits</Typography><Button size="small" onClick={()=>void request(`/v1/admin/customers/${u.id}/invite`,{method:'POST'})}>Invite</Button><Button size="small" onClick={()=>void request(`/v1/admin/customers/${u.id}/reset-password`,{method:'POST'})}>Reset password</Button><Button size="small" onClick={()=>void request(`/v1/admin/customers/${u.id}/${u.lifecycle==='suspended'?'restore':'suspend'}`,{method:'POST'})}>{u.lifecycle==='suspended'?'Restore':'Disable'}</Button></Paper>)}</Stack>}
function Credits(){return <Directory title="Credits" endpoint="/v1/admin/credits/stats" text="Credit balance and ledger adjustments are available per user in User Management."/>}function Samples(){return <Directory title="Samples" endpoint="/v1/admin/samples/stats" text="Captured and uploaded sample streams."/>}function Directory({title,endpoint,text}:{title:string;endpoint:string;text:string}){const[data,setData]=useState('');useEffect(()=>{void request<unknown>(endpoint).then(x=>setData(JSON.stringify(x))).catch(e=>setData(e.message))},[endpoint]);return <Stack spacing={2}><Typography variant="h4">{title}</Typography><Typography>{text}</Typography><Paper sx={{p:2}}><Typography variant="body2">{data}</Typography></Paper></Stack>}
