// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, describe, expect, it, vi } from 'vitest';
import type { PsiuStatus } from '@wally/contracts';
import { ControllerPage } from './ControllerPage.js';
vi.mock('../auth.js',()=>({accessToken:vi.fn(async()=> 'token')}));
const ready:PsiuStatus={uid:'uid-1',uptimeMs:1,sampleRateHz:48000,recording:false,xlr:false,bufferCount:0,recorderState:'idle',pagesWritten:0,droppedHalves:0,badBlockCount:0,dmaErrors:0,i2sErrors:0,recordingCount:0};const recording={...ready,recording:true};const client={getStatus:vi.fn(async()=>ready),startCapture:vi.fn(async()=>recording),stopCapture:vi.fn(async()=>ready),getCompletedCapture:vi.fn(async()=>new Blob(['RIFF____WAVE'],{type:'audio/wav'}))};vi.mock('../features/controller/psiuClient.js',()=>({createPsuClient:()=>client,PsiuUnavailableError:class PsiuUnavailableError extends Error{}}));
afterEach(()=>{cleanup();vi.unstubAllGlobals();vi.clearAllMocks();});
const units=[{id:'unit-1',serialNumber:'serial-1',uid:'uid-1',status:'enabled' as const}];const systems=[{id:'system-1',name:'Reference system',notes:'',components:{turntable:'TT',tonearm:'Arm',cartridge:'Cart'},active:true,createdAt:'2026-01-01T00:00:00.000Z'}];
function renderController(){vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>{const url=String(input);const payload=url.endsWith('/v1/reports/definitions')?[{key:'tracking-error',displayName:'Tracking Error',algorithmVersion:'1',presets:[{key:'rti',displayName:'RTI',version:'1',notice:''}]}]:url.includes('/v1/reports?')?{items:[]}:url.endsWith('/v1/me/systems')?systems:[];return new Response(JSON.stringify(payload),{status:200,headers:{'content-type':'application/json'}});}));return render(<MemoryRouter><ControllerPage units={units} systems={systems}/></MemoryRouter>);}
describe('PSIU-only capture process flow',()=>{it('has no manual WAV picker',async()=>{renderController();await screen.findByRole('button',{name:'Start capture'});expect(screen.queryByText('Upload and Process')).toBeNull();expect(screen.queryByRole('button',{name:'Select WAV files'})).toBeNull();});it('opens process dialog only after stop and discard returns ready',async()=>{renderController();fireEvent.click(await screen.findByRole('button',{name:'Start capture'}));fireEvent.click(await screen.findByRole('button',{name:'Stop capture'}));expect((await screen.findByRole('dialog')).textContent).toContain('Process this sample');fireEvent.click(screen.getByRole('button',{name:'Discard'}));});});
