import { Alert, Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, Paper, TextField, Typography } from '@mui/material';
import type { CreateReportRequest, ReportDefinition, YawGeometryParameters } from '@wally/contracts';
import { useState } from 'react';
import { WallySelect } from '../designSystemSelect.js';

const defaultYawGeometry: YawGeometryParameters={effectiveLengthMm:280,offsetAngleDeg:19.495,overhangMm:14.63,mountYawDeg:0};
const numeric=(value:string,fallback:number)=>Number.isFinite(Number(value))?Number(value):fallback;

/** Report selection is shared by the controller and report workflow tests. No file selection occurs here. */
export function ReportPicker({ open, definitions, onSubmit, onClose, error, cancelLabel='Cancel' }: { open: boolean; definitions: ReportDefinition[]; onSubmit: (reports: CreateReportRequest['reports']) => Promise<void>; onClose: () => void; error?: string; cancelLabel?:string }) {
  const [selected, setSelected] = useState<Record<string, string>>({});
  const [yawGeometry,setYawGeometry]=useState<YawGeometryParameters>(defaultYawGeometry);
  const count = Object.keys(selected).length;
  const field=(label:keyof YawGeometryParameters,description:string)=><TextField key={label} label={description} type="number" value={yawGeometry[label]} onChange={event=>setYawGeometry(current=>({...current,[label]:numeric(event.target.value,current[label])}))} inputProps={{step:'any'}} fullWidth sx={{mt:1}}/>;
  const submit=()=>onSubmit(Object.entries(selected).map(([definitionKey,presetKey])=>definitionKey==='tracking-error'?{definitionKey,presetKey,yawGeometry}:{definitionKey,presetKey}));
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>Process this sample</DialogTitle><DialogContent><Typography color="text.secondary" mb={2}>Choose reports to run after this PSIU capture is transferred and verified.</Typography>{error&&<Alert severity="error">{error}</Alert>}{definitions.map(definition=>{const presetKey=selected[definition.key]??definition.presets[0]?.key??'';const active=Boolean(selected[definition.key]);const yaw=definition.key==='tracking-error';return <Paper key={definition.key} variant="outlined" sx={{p:2,mb:1}}><FormControlLabel control={<Checkbox checked={active} onChange={event=>setSelected(current=>{const next={...current};if(event.target.checked)next[definition.key]=current[definition.key]??definition.presets[0]?.key??'';else delete next[definition.key];return next;})}/>} label={definition.displayName}/>{active&&<WallySelect label={`${definition.displayName} preset`} value={presetKey} onChange={value=>setSelected(current=>({...current,[definition.key]:value}))} options={definition.presets.map(item=>({value:item.key,label:`${item.displayName} v${item.version}`}))}/>} {active&&yaw&&<><Typography variant="subtitle2" mt={2}>Yaw geometry</Typography>{field('effectiveLengthMm','Effective length (mm)')}{field('offsetAngleDeg','Offset angle (°)')}{field('overhangMm','Overhang (mm)')}{field('mountYawDeg','Mount yaw (°)')}</>} {active&&definition.presets.find(item=>item.key===presetKey)?.notice&&<Alert severity="info">{definition.presets.find(item=>item.key===presetKey)?.notice}</Alert>}</Paper>;})}</DialogContent><DialogActions><Button onClick={onClose}>{cancelLabel}</Button><Button disabled={!count} variant="contained" onClick={()=>void submit()}>Queue {count?`${count} `:''}report{count===1?'':'s'}</Button></DialogActions></Dialog>;
}
