import { Alert, Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, Paper, Typography } from '@mui/material';
import type { CreateReportRequest, ReportDefinition } from '@wally/contracts';
import { useState } from 'react';
import { WallySelect } from '../designSystemSelect.js';

/** Report selection is shared by the controller and report workflow tests. No file selection occurs here. */
export function ReportPicker({ open, definitions, onSubmit, onClose, error, cancelLabel='Cancel' }: { open: boolean; definitions: ReportDefinition[]; onSubmit: (reports: CreateReportRequest['reports']) => Promise<void>; onClose: () => void; error?: string; cancelLabel?:string }) {
  const [selected, setSelected] = useState<Record<string, string>>({});
  const count = Object.keys(selected).length;
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>Process this sample</DialogTitle><DialogContent><Typography color="text.secondary" mb={2}>Choose reports to run after this PSIU capture is transferred and verified.</Typography>{error&&<Alert severity="error">{error}</Alert>}{definitions.map(definition=>{const presetKey=selected[definition.key]??definition.presets[0]?.key??'';const active=Boolean(selected[definition.key]);return <Paper key={definition.key} variant="outlined" sx={{p:2,mb:1}}><FormControlLabel control={<Checkbox checked={active} onChange={event=>setSelected(current=>{const next={...current};if(event.target.checked)next[definition.key]=current[definition.key]??definition.presets[0]?.key??'';else delete next[definition.key];return next;})}/>} label={definition.displayName}/>{active&&<WallySelect label={`${definition.displayName} preset`} value={presetKey} onChange={value=>setSelected(current=>({...current,[definition.key]:value}))} options={definition.presets.map(item=>({value:item.key,label:`${item.displayName} v${item.version}`}))}/>} {active&&definition.presets.find(item=>item.key===presetKey)?.notice&&<Alert severity="info">{definition.presets.find(item=>item.key===presetKey)?.notice}</Alert>}</Paper>;})}</DialogContent><DialogActions><Button onClick={onClose}>{cancelLabel}</Button><Button disabled={!count} variant="contained" onClick={()=>void onSubmit(Object.entries(selected).map(([definitionKey,presetKey])=>({definitionKey,presetKey})))}>Queue {count?`${count} `:''}report{count===1?'':'s'}</Button></DialogActions></Dialog>;
}
