import { Alert, Button, Paper, Stack, TextField, Typography } from '@mui/material';
import { useEffect, useState } from 'react';
import type { CreditsResponse, MeResponse, UserSystem } from '@wally/contracts';
import { accessToken } from '../auth.js';
import { apiBaseUrl as api } from '../runtimeConfig.js';
async function request<T>(path:string,init?:RequestInit):Promise<T>{const token=await accessToken();const r=await fetch(`${api}${path}`,{...init,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...init?.headers}});if(!r.ok)throw Error((await r.json().catch(()=>({}))).message??'Request failed.');return r.status===204?undefined as T:r.json();}
export function ProfilePage({me,onSaved}:{me:MeResponse;onSaved:()=>void}){const[firstName,setFirstName]=useState(me.firstName??'');const[lastName,setLastName]=useState(me.lastName??'');const[message,setMessage]=useState('');return <Stack spacing={2}><Typography variant="h4">Profile</Typography><Paper sx={{p:2}}><Stack spacing={2}><TextField label="First name" value={firstName} onChange={e=>setFirstName(e.target.value)}/><TextField label="Last name" value={lastName} onChange={e=>setLastName(e.target.value)}/><Button variant="contained" onClick={async()=>{try{await request('/v1/me/profile',{method:'PUT',body:JSON.stringify({firstName,lastName})});setMessage('Profile saved.');onSaved();}catch(e){setMessage(e instanceof Error?e.message:'Profile update failed.')}}}>Save profile</Button>{message&&<Alert severity="info">{message}</Alert>}</Stack></Paper></Stack>}
export function SystemsPage(){const[systems,setSystems]=useState<UserSystem[]>([]);const[name,setName]=useState('');const[turntable,setTurntable]=useState('');const[tonearm,setTonearm]=useState('');const[cartridge,setCartridge]=useState('');const[headshell,setHeadshell]=useState('');const[notes,setNotes]=useState('');const[message,setMessage]=useState('');const load=()=>request<UserSystem[]>('/v1/me/systems').then(setSystems).catch(e=>setMessage(e.message));useEffect(()=>{void load()},[]);return <Stack spacing={2}><Typography variant="h4">Systems</Typography><Typography color="text.secondary">A system records the equipment used for a capture.</Typography><Paper sx={{p:2}}><Stack spacing={2}><TextField label="System name" value={name} onChange={e=>setName(e.target.value)}/><TextField label="Turntable" value={turntable} onChange={e=>setTurntable(e.target.value)}/><TextField label="Tonearm" value={tonearm} onChange={e=>setTonearm(e.target.value)}/><TextField label="Cartridge" value={cartridge} onChange={e=>setCartridge(e.target.value)}/><TextField label="Headshell (optional)" value={headshell} onChange={e=>setHeadshell(e.target.value)}/><TextField label="Notes" value={notes} onChange={e=>setNotes(e.target.value)} multiline minRows={2}/><Button variant="contained" onClick={async()=>{try{await request('/v1/me/systems',{method:'POST',body:JSON.stringify({name,notes,components:{turntable,tonearm,cartridge,headshell},active:true})});setName('');setTurntable('');setTonearm('');setCartridge('');setHeadshell('');setNotes('');await load();}catch(e){setMessage(e instanceof Error?e.message:'System creation failed.')}}}>Create active system</Button>{message&&<Alert severity="info">{message}</Alert>}</Stack></Paper>{systems.map(s=><Paper key={s.id} sx={{p:2}}><Typography variant="h6">{s.name}{s.active?' · Active':''}</Typography><Typography>{s.components.turntable} · {s.components.tonearm} · {s.components.cartridge}{s.components.headshell?` · ${s.components.headshell}`:''}</Typography><Typography color="text.secondary">{s.notes}</Typography>{!s.active&&<Button onClick={async()=>{await request(`/v1/me/systems/${s.id}/active`,{method:'POST'});await load();}}>Make active</Button>}</Paper>)}</Stack>}
export function CreditsPage(){const[data,setData]=useState<CreditsResponse>();const[message,setMessage]=useState('');useEffect(()=>{void request<CreditsResponse>('/v1/me/credits').then(setData).catch(e=>setMessage(e.message));},[]);return <Stack spacing={2}><Typography variant="h4">Credits</Typography><Paper sx={{p:2}}><Typography variant="h3">{data?.balance??'—'}</Typography><Typography color="text.secondary">Available credits</Typography></Paper>{message&&<Alert severity="info">{message}</Alert>}<Paper sx={{p:2}}><Typography variant="h6">History</Typography>{data?.entries.length?data.entries.map(e=><Typography key={e.id}>{new Date(e.createdAt).toLocaleString()} · {e.delta>0?'+':''}{e.delta} · {e.kind}{e.note?` — ${e.note}`:''}</Typography>):<Typography color="text.secondary">No credit activity yet.</Typography>}</Paper></Stack>}
export function ReportsPage(){return <Stack spacing={2}><Typography variant="h4">Reports</Typography><Paper sx={{p:2}}><Typography variant="h6">Uploads and reports</Typography><Typography color="text.secondary">Reports are not selected yet. Report products and credit usage will be added in a later release.</Typography></Paper></Stack>}
