import assert from 'node:assert/strict';
import test from 'node:test';
import { request as httpRequest } from 'node:http';
import { createProductionServer } from './production.js';

process.env.COGNITO_USER_POOL_ID = 'pool'; process.env.COGNITO_WEB_CLIENT_ID = 'client';
const repository = { async findActivePrincipal(){ return { id:'admin',email:'admin@example.com',role:'admin' as const,lifecycle:'active',emailConfirmedAt:new Date() }; } };
function server(adminData: Record<string, unknown>, role:'admin'|'user'='admin') { return createProductionServer({ pool:{} as never, repository:{...repository,async findActivePrincipal(){return role==='admin'?repository.findActivePrincipal():{id:'user',email:'u@example.com',role:'user' as const,lifecycle:'active',emailConfirmedAt:new Date()};}} as never, adminData:adminData as never, verify:async()=>({subject:'subject',roles:[role]}) }); }
function call(s: ReturnType<typeof createProductionServer>, method:string, path:string, body?:unknown) { const a=s.address(); if(!a||typeof a==='string')throw Error('server unavailable'); return new Promise<{status:number;body:string}>((resolve,reject)=>{const r=httpRequest({host:'127.0.0.1',port:a.port,path,method,headers:{authorization:'Bearer token','content-type':'application/json'}},x=>{let text='';x.on('data',q=>text+=q);x.on('end',()=>resolve({status:x.statusCode??0,body:text}));});r.on('error',reject);if(body)r.write(JSON.stringify(body));r.end();}); }
async function run(s:ReturnType<typeof createProductionServer>, fn:()=>Promise<void>){await new Promise<void>(r=>s.listen(0,'127.0.0.1',r));try{await fn();}finally{await new Promise<void>(r=>s.close(()=>r()));}}

test('admin directory supports typeahead, bounds, detail, profile, credit and sample endpoints', async () => {
  const calls:string[]=[]; const data={ async users(v:unknown){calls.push('users');return v;},async typeahead(q:string){calls.push(`type:${q}`);return[];},async user(){calls.push('user');return{id:'00000000-0000-4000-8000-000000000001'};},async updateUser(_id:string,_actor:string,value:unknown){calls.push(`update:${JSON.stringify(value)}`);return{};},async credits(){calls.push('credits');return{};},async adjustCredits(_id:string,_actor:string,value:{delta:number;note:string}){calls.push(`adjust:${value.delta}:${value.note}`);return{};},async creditStats(){calls.push('stats');return[];},async samples(){calls.push('samples');return{};},async sampleStats(){return{};},async units(){return[];} }; const s=server(data);
  await run(s,async()=>{assert.equal((await call(s,'GET','/v1/admin/users/typeahead?q=al')).status,200);assert.equal((await call(s,'GET','/v1/admin/users?limit=0')).status,400);assert.equal((await call(s,'GET','/v1/admin/users/00000000-0000-4000-8000-000000000001')).status,200);assert.equal((await call(s,'PUT','/v1/admin/users/00000000-0000-4000-8000-000000000001',{firstName:'Ada',address:{line1:'1 Main',countryCode:'US'}})).status,200);assert.equal((await call(s,'POST','/v1/admin/users/00000000-0000-4000-8000-000000000001/credits',{delta:-1,note:'Correction'})).status,201);assert.equal((await call(s,'GET','/v1/admin/samples?offset=0&limit=1')).status,200);assert.deepEqual(calls,['type:al','user','update:{"firstName":"Ada","address":{"line1":"1 Main","countryCode":"US"}}','adjust:-1:Correction','samples']);});
});

test('non-admin cannot read admin sample or user data', async () => { const s=server({},'user'); await run(s,async()=>{assert.equal((await call(s,'GET','/v1/admin/users')).status,403);assert.equal((await call(s,'GET','/v1/admin/samples')).status,403);}); });
