import { randomUUID } from 'node:crypto';
import { Pool, type PoolClient } from 'pg';
import type { CustomerSummary, CustomerUnit, MeResponse, PsiuUnitStatus, Role } from '@wally/contracts';
import { HttpError } from './auth.js';

export type CognitoReconciliationJob = { id: string; customerId: string; action: 'invite_cleanup' | 'archive_delete'; email: string; cognitoSubject?: string };

export interface AccountRepository {
  findActivePrincipal(subject: string): Promise<{ id: string; role: Role; lifecycle: string } | undefined>;
  me(id: string): Promise<MeResponse | undefined>;
  customers(): Promise<CustomerSummary[]>;
  units(): Promise<CustomerUnit[]>;
  customer(id: string): Promise<CustomerSummary | undefined>;
  createCustomer(email: string, actorId: string, requestId?: string): Promise<CustomerSummary>;
  createUnit(serialNumber: string, uid: string, actorId: string, requestId?: string): Promise<CustomerUnit>;
  setUnitStatus(unitId: string, status: PsiuUnitStatus, actorId: string, requestId?: string): Promise<void>;
  assign(unitId: string, customerId: string, actorId: string, requestId?: string): Promise<void>;
  deassign(unitId: string, actorId: string, requestId?: string): Promise<void>;
  markInvited(customerId: string, subject: string, actorId: string, requestId?: string): Promise<void>;
  recordInviteCleanup(customerId: string, email: string, subject: string, actorId: string, requestId?: string): Promise<CognitoReconciliationJob>;
  pendingCognitoJob(customerId: string, action: CognitoReconciliationJob['action']): Promise<CognitoReconciliationJob | undefined>;
  completeCognitoJob(job: CognitoReconciliationJob, actorId: string, requestId?: string): Promise<void>;
  activate(subject: string): Promise<void>;
  setCustomerLifecycle(customerId: string, lifecycle: 'suspended' | 'ready' | 'active', actorId: string, requestId?: string): Promise<{ email: string; cognitoSubject?: string }>;
  archive(customerId: string, actorId: string, requestId?: string): Promise<{ email: string; cognitoSubject?: string; job?: CognitoReconciliationJob }>;
}

type UserRow = { id: string; email: string; role: Role; lifecycle: MeResponse['lifecycle']; invited_at: Date | null; cognito_subject?: string | null };
type UnitRow = { id: string; serial_number: string; opaque_uid: string; status: PsiuUnitStatus; assigned_at: Date | null };
type JobRow = { id: string; customer_id: string; action: CognitoReconciliationJob['action']; email: string; cognito_subject: string | null };

export class PostgresAccountRepository implements AccountRepository {
  constructor(private readonly pool: Pool) {}
  async findActivePrincipal(subject: string) { const r = await this.pool.query<{ id: string; role: Role; lifecycle: string }>(`select id, role, lifecycle from users where cognito_subject=$1 and lifecycle in ('invited','active')`, [subject]); return r.rows[0]; }
  async me(id: string): Promise<MeResponse | undefined> { const r = await this.pool.query<UserRow>(`select id,email,role,lifecycle,invited_at from users where id=$1`, [id]); if (!r.rowCount) return undefined; const u = r.rows[0]; return { id:u.id,email:u.email,role:u.role,lifecycle:u.lifecycle,units:await this.unitsFor(id),emailChangeAvailable:false }; }
  async customers(): Promise<CustomerSummary[]> { const r = await this.pool.query<UserRow>(`select id,email,role,lifecycle,invited_at from users where role='user' order by email`); return Promise.all(r.rows.map(u => this.summary(u))); }
  async customer(id: string): Promise<CustomerSummary | undefined> { const r = await this.pool.query<UserRow>(`select id,email,role,lifecycle,invited_at from users where id=$1 and role='user'`, [id]); return r.rowCount ? this.summary(r.rows[0]) : undefined; }
  private async summary(u: UserRow): Promise<CustomerSummary> { return { id:u.id,email:u.email,lifecycle:u.lifecycle,invitedAt:u.invited_at?.toISOString(),units:await this.unitsFor(u.id) }; }
  async units(): Promise<CustomerUnit[]> { return this.allUnits(); }
  async createCustomer(email:string,actor:string,requestId?:string):Promise<CustomerSummary> { const id=randomUUID(); try { const r=await this.pool.query<UserRow>(`insert into users(id,email,cognito_subject,role,lifecycle,account_status) values($1,$2,null,'user','draft',null) returning id,email,role,lifecycle,invited_at`,[id,email]); await this.audit(actor,'customer.created','user',id,requestId,{email}); return {id:r.rows[0].id,email:r.rows[0].email,lifecycle:r.rows[0].lifecycle,units:[]}; } catch (error) { if (isUniqueViolation(error)) throw new HttpError(409,'Email is reserved by an existing or archived customer.'); throw error; } }
  async createUnit(serial:string,uid:string,actor:string,requestId?:string):Promise<CustomerUnit>{const id=randomUUID();const r=await this.pool.query<UnitRow>(`insert into psiu_units(id,serial_number,opaque_uid,created_by) values($1,$2,$3,$4) returning id,serial_number,opaque_uid,status,null::timestamptz assigned_at`,[id,serial,uid,actor]);await this.audit(actor,'psiu.created','psiu_unit',id,requestId,{serialNumber:serial,uid});return unit(r.rows[0]);}
  async setUnitStatus(id:string,status:PsiuUnitStatus,actor:string,requestId?:string):Promise<void>{const r=await this.pool.query(`update psiu_units set status=$2,disabled_at=case when $2='disabled' then now() else null end,disabled_by=case when $2='disabled' then $3 else null end where id=$1`,[id,status,actor]);if(!r.rowCount)throw new HttpError(404,'PSIU unit not found.');await this.audit(actor,`psiu.${status}`,'psiu_unit',id,requestId,{});}
  async assign(unitId:string,customerId:string,actor:string,requestId?:string):Promise<void>{const c=await this.pool.connect();try{await c.query('begin');const unitRow=await c.query(`select id from psiu_units where id=$1 and status='enabled' for update`,[unitId]);if(!unitRow.rowCount)throw new HttpError(400,'Enabled PSIU unit required.');const customer=await c.query(`select id from users where id=$1 and role='user' and lifecycle in ('draft','ready','invited','active') for update`,[customerId]);if(!customer.rowCount)throw new HttpError(400,'Assignable customer required.');await c.query(`update psiu_assignments set unassigned_at=now(),unassigned_by=$2 where psiu_unit_id=$1 and unassigned_at is null`,[unitId,actor]);await c.query(`update psiu_assignments set unassigned_at=now(),unassigned_by=$2 where user_id=$1 and unassigned_at is null`,[customerId,actor]);await c.query(`insert into psiu_assignments(id,psiu_unit_id,user_id,assigned_by) values($1,$2,$3,$4)`,[randomUUID(),unitId,customerId,actor]);await this.auditClient(c,actor,'psiu.assigned','psiu_unit',unitId,requestId,{customerId});await c.query('commit');}catch(error){await c.query('rollback');throw error;}finally{c.release();}}
  async deassign(id:string,actor:string,requestId?:string):Promise<void>{const r=await this.pool.query(`update psiu_assignments set unassigned_at=now(),unassigned_by=$2 where psiu_unit_id=$1 and unassigned_at is null`,[id,actor]);if(!r.rowCount)throw new HttpError(404,'Active PSIU assignment not found.');await this.audit(actor,'psiu.deassigned','psiu_unit',id,requestId,{});}
  async markInvited(id:string,subject:string,actor:string,requestId?:string):Promise<void>{const r=await this.pool.query(`update users set cognito_subject=$2,lifecycle='invited',account_status='provisioned',invited_at=now() where id=$1 and lifecycle in ('draft','ready')`,[id,subject]);if(!r.rowCount)throw new HttpError(409,'Customer cannot be invited.');await this.audit(actor,'customer.invited','user',id,requestId,{});}
  async recordInviteCleanup(customerId:string,email:string,subject:string,actor:string,requestId?:string):Promise<CognitoReconciliationJob>{const job=await this.createJob(customerId,'invite_cleanup',email,subject);await this.audit(actor,'cognito.invite_cleanup_queued','user',customerId,requestId,{jobId:job.id});return job;}
  async pendingCognitoJob(customerId:string,action:CognitoReconciliationJob['action']):Promise<CognitoReconciliationJob|undefined>{const r=await this.pool.query<JobRow>(`select id,customer_id,action,email,cognito_subject from cognito_reconciliation_jobs where customer_id=$1 and action=$2 and completed_at is null`,[customerId,action]);return r.rowCount?job(r.rows[0]):undefined;}
  async completeCognitoJob(value:CognitoReconciliationJob,actor:string,requestId?:string):Promise<void>{await this.pool.query(`update cognito_reconciliation_jobs set completed_at=now(),last_error=null where id=$1 and completed_at is null`,[value.id]);await this.audit(actor,`cognito.${value.action}_completed`,'user',value.customerId,requestId,{jobId:value.id});}
  async activate(subject:string):Promise<void>{const r=await this.pool.query<{id:string}>(`update users set lifecycle='active',account_status='active' where cognito_subject=$1 and lifecycle='invited' returning id`,[subject]);if(r.rowCount)await this.audit(r.rows[0].id,'customer.activated','user',r.rows[0].id,undefined,{});}
  async setCustomerLifecycle(id:string,lifecycle:'suspended'|'ready'|'active',actor:string,requestId?:string):Promise<{email:string;cognitoSubject?:string}>{const r=await this.pool.query<{email:string;cognito_subject:string|null}>(`update users set lifecycle=$2,account_status=case when $2='suspended' then 'suspended' when $2='active' then 'active' else account_status end where id=$1 and role='user' and lifecycle <> 'cancelled' returning email,cognito_subject`,[id,lifecycle]);if(!r.rowCount)throw new HttpError(404,'Customer not found.');await this.audit(actor,`customer.${lifecycle}`,'user',id,requestId,{});return{email:r.rows[0].email,cognitoSubject:r.rows[0].cognito_subject??undefined};}
  async archive(id:string,actor:string,requestId?:string):Promise<{email:string;cognitoSubject?:string;job?:CognitoReconciliationJob}>{const c=await this.pool.connect();try{await c.query('begin');const r=await c.query<{email:string;cognito_subject:string|null}>(`update users set lifecycle='cancelled',archived_at=now(),account_status='cancelled' where id=$1 and role='user' and lifecycle <> 'cancelled' returning email,cognito_subject`,[id]);if(!r.rowCount)throw new HttpError(404,'Customer not found.');await c.query(`update psiu_assignments set unassigned_at=now(),unassigned_by=$2 where user_id=$1 and unassigned_at is null`,[id,actor]);const pending=r.rows[0].cognito_subject?await this.createJob(id,'archive_delete',r.rows[0].email,r.rows[0].cognito_subject,c):undefined;await this.auditClient(c,actor,'customer.archived','user',id,requestId,pending?{jobId:pending.id}:{});await c.query('commit');return{email:r.rows[0].email,cognitoSubject:r.rows[0].cognito_subject??undefined,job:pending};}catch(error){await c.query('rollback');throw error;}finally{c.release();}}
  private async createJob(customerId:string,action:CognitoReconciliationJob['action'],email:string,subject:string,client:Pool|PoolClient=this.pool):Promise<CognitoReconciliationJob>{const id=randomUUID();try{const r=await client.query<JobRow>(`insert into cognito_reconciliation_jobs(id,customer_id,action,email,cognito_subject) values($1,$2,$3,$4,$5) returning id,customer_id,action,email,cognito_subject`,[id,customerId,action,email,subject]);return job(r.rows[0]);}catch(error){if(!isUniqueViolation(error))throw error;const r=await client.query<JobRow>(`select id,customer_id,action,email,cognito_subject from cognito_reconciliation_jobs where customer_id=$1 and action=$2 and completed_at is null`,[customerId,action]);return job(r.rows[0]);}}
  private async unitsFor(userId:string){const r=await this.pool.query<UnitRow>(`select p.id,p.serial_number,p.opaque_uid,p.status,a.assigned_at from psiu_units p join psiu_assignments a on a.psiu_unit_id=p.id and a.unassigned_at is null where a.user_id=$1 order by a.assigned_at desc`,[userId]);return r.rows.map(unit);}
  private async allUnits(){const r=await this.pool.query<UnitRow>(`select p.id,p.serial_number,p.opaque_uid,p.status,a.assigned_at from psiu_units p left join psiu_assignments a on a.psiu_unit_id=p.id and a.unassigned_at is null order by p.serial_number`);return r.rows.map(unit);}
  private audit(actor:string,action:string,type:string,id:string,requestId:string|undefined,metadata:Record<string,string>){return this.auditClient(this.pool,actor,action,type,id,requestId,metadata);}
  private auditClient(c:Pool|PoolClient,actor:string,action:string,type:string,id:string,requestId:string|undefined,metadata:Record<string,string>){return c.query(`insert into audit_events(id,actor_id,action,subject_type,subject_id,request_id,metadata) values($1,$2,$3,$4,$5,$6,$7::jsonb)`,[randomUUID(),actor,action,type,id,requestId??null,JSON.stringify(metadata)]);}
}
function job(row:JobRow):CognitoReconciliationJob{return{id:row.id,customerId:row.customer_id,action:row.action,email:row.email,cognitoSubject:row.cognito_subject??undefined};}
function unit(row:UnitRow):CustomerUnit{return{id:row.id,serialNumber:row.serial_number,uid:row.opaque_uid,status:row.status,assignedAt:row.assigned_at?.toISOString()};}
function isUniqueViolation(error:unknown):boolean{return typeof error==='object'&&error!==null&&'code' in error&&(error as {code?:string}).code==='23505';}
