import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { HttpError } from './auth.js';

const PAGE_MAX=100;
type Page={limit?:number;offset?:number};
function page(value:Page={}){const limit=Math.max(1,Math.min(PAGE_MAX,Number(value.limit??25)||25));const offset=Math.max(0,Number(value.offset??0)||0);return{limit,offset};}
export class PostgresAdminDataRepository {
  constructor(private readonly pool:Pool){}
  async touchLastActive(ownerId:string){await this.pool.query(`update users set last_active_at=now() where id=$1 and (last_active_at is null or last_active_at < now()-interval '15 minutes')`,[ownerId]);}
  async users(value:{q?:string}&Page={}){const p=page(value);const q=(value.q??'').trim();const term=`%${q.replace(/[%_\\]/g,'\\$&')}%`;const r=await this.pool.query(`select u.id,u.email,u.first_name,u.last_name,u.lifecycle,u.created_at,u.last_active_at,coalesce((select l.balance_after from credit_ledger_entries l where l.owner_id=u.id order by l.created_at desc limit 1),0) balance,coalesce(json_agg(json_build_object('id',p.id,'serialNumber',p.serial_number,'status',p.status)) filter(where p.id is not null),'[]') units from users u left join psiu_assignments a on a.user_id=u.id and a.unassigned_at is null left join psiu_units p on p.id=a.psiu_unit_id where u.role='user' and ($1='' or u.email ilike $2 escape '\\' or coalesce(u.first_name,'') ilike $2 escape '\\' or coalesce(u.last_name,'') ilike $2 escape '\\' or exists(select 1 from psiu_assignments aa join psiu_units pp on pp.id=aa.psiu_unit_id where aa.user_id=u.id and aa.unassigned_at is null and pp.serial_number ilike $2 escape '\\')) group by u.id order by u.email limit $3 offset $4`,[q,term,p.limit,p.offset]);return{items:r.rows,limit:p.limit,offset:p.offset};}
  async typeahead(q:string){const term=`%${q.trim().replace(/[%_\\]/g,'\\$&')}%`;if(q.trim().length<2)return[];const r=await this.pool.query(`select id,email,first_name,last_name from users where role='user' and lifecycle in ('draft','ready','invited','active') and (email ilike $1 escape '\\' or coalesce(first_name,'') ilike $1 escape '\\' or coalesce(last_name,'') ilike $1 escape '\\') order by email limit 20`,[term]);return r.rows.map(x=>({...x,displayName:[x.first_name,x.last_name].filter(Boolean).join(' ')||x.email}));}
  async adjustCredits(ownerId:string,actorId:string,value:{delta:number;note:string;kind?:'grant'|'administrative_adjustment'}){const delta=Math.trunc(value.delta);const note=value.note?.trim();if(!delta||!note||note.length>2000)throw new HttpError(400,'Nonblank note and nonzero credit amount required.');const c=await this.pool.connect();try{await c.query('begin');await c.query(`select id from users where id=$1 for update`,[ownerId]);const prior=await c.query<{balance_after:number}>(`select balance_after from credit_ledger_entries where owner_id=$1 order by created_at desc limit 1 for update`,[ownerId]);const balance=(prior.rows[0]?.balance_after??0)+delta;if(balance<0)throw new HttpError(409,'Credit balance cannot be negative.');const r=await c.query(`insert into credit_ledger_entries(id,owner_id,kind,delta,balance_after,note,actor_id) values($1,$2,$3,$4,$5,$6,$7) returning id,kind,delta,balance_after,note,created_at`,[randomUUID(),ownerId,value.kind??'administrative_adjustment',delta,balance,note,actorId]);await c.query('commit');return r.rows[0];}catch(e){await c.query('rollback');throw e;}finally{c.release();}}
  async samples(value:{limit?:number;offset?:number;ownerId?:string;psiuUnitId?:string;source?:string;state?:string}={}){const p=page(value);const r=await this.pool.query(`select s.id,s.owner_id,s.psiu_unit_id,s.source,s.upload_state,s.metadata,s.system_snapshot,s.recorded_at,s.created_at,s.uploaded_at,u.email,p.serial_number from samples s join users u on u.id=s.owner_id join psiu_units p on p.id=s.psiu_unit_id where ($1::uuid is null or s.owner_id=$1) and ($2::uuid is null or s.psiu_unit_id=$2) and ($3::text is null or s.source=$3) and ($4::text is null or s.upload_state=$4) order by s.created_at desc limit $5 offset $6`,[value.ownerId??null,value.psiuUnitId??null,value.source??null,value.state??null,p.limit,p.offset]);return{items:r.rows,limit:p.limit,offset:p.offset};}
  async sampleStats(adminId:string){const r=await this.pool.query<{total:string;d7:string;d14:string;d30:string;ytd:string;fresh:string}>(`select count(*) total,count(*) filter(where created_at>=now()-interval '7 days') d7,count(*) filter(where created_at>=now()-interval '14 days') d14,count(*) filter(where created_at>=now()-interval '30 days') d30,count(*) filter(where created_at>=date_trunc('year',now())) ytd,count(*) filter(where created_at>coalesce((select admin_samples_viewed_at from users where id=$1),'epoch')) fresh from samples`,[adminId]);await this.pool.query(`update users set admin_samples_viewed_at=now() where id=$1`,[adminId]);return r.rows[0];}
}
