import { createHash, randomUUID } from 'node:crypto';
import type { CreateReportRequest, ReportDefinition, ReportHistoryItem, ReportHistoryPage } from '@wally/contracts';
import { Pool } from 'pg';
import { HttpError } from './auth.js';

const WAV_TYPES=new Set(['audio/wav','audio/x-wav','audio/wave']);
type DefinitionRow={id:string;key:string;display_name:string;algorithm_version:string;preset_id:string;preset_key:string;preset_name:string;preset_version:string;snapshot:{notice?:string}};
type ReportCursor={createdAt:string;id:string};
export function encodeReportCursor(value:ReportCursor){return Buffer.from(JSON.stringify(value)).toString('base64url');}
export function decodeReportCursor(value:string):ReportCursor{try{if(!/^[A-Za-z0-9_-]{1,1024}$/.test(value))throw Error();const parsed=JSON.parse(Buffer.from(value,'base64url').toString('utf8'));if(!parsed||typeof parsed!=='object'||Object.keys(parsed).length!==2||typeof parsed.createdAt!=='string'||!Number.isFinite(Date.parse(parsed.createdAt))||typeof parsed.id!=='string'||!uuid(parsed.id))throw Error();return{createdAt:new Date(parsed.createdAt).toISOString(),id:parsed.id};}catch{throw new HttpError(400,'cursor is invalid.');}}
export class PostgresReportRepository {
  constructor(private readonly pool:Pool){}
  async definitions():Promise<ReportDefinition[]>{
    const r=await this.pool.query<DefinitionRow>(`select d.id,d.key,d.display_name,d.algorithm_version,p.id preset_id,p.key preset_key,p.display_name preset_name,p.version preset_version,p.snapshot from report_definitions d join report_presets p on p.definition_id=d.id where d.enabled and p.enabled order by d.key,p.display_name`);
    const out=new Map<string,ReportDefinition>(); for(const x of r.rows){let d=out.get(x.key);if(!d){d={key:x.key,displayName:x.display_name,algorithmVersion:x.algorithm_version,presets:[]};out.set(x.key,d)}d.presets.push({key:x.preset_key,displayName:x.preset_name,version:x.preset_version,notice:String(x.snapshot.notice??'')})} return[...out.values()];
  }
  async create(ownerId:string,value:CreateReportRequest):Promise<{requestId:string;reports:ReportHistoryItem[]}> {
    if(!value||!Array.isArray(value.reports)||!value.reports.length||value.reports.length>16)throw new HttpError(400,'Select one to sixteen reports.');
    if(typeof value.idempotencyKey!=='string'||!value.idempotencyKey.trim()||value.idempotencyKey.length>128)throw new HttpError(400,'Valid idempotency key required.');
    if(!uuid(value.batchId))throw new HttpError(400,'Valid upload batch required.');
    const selections=value.reports.map(x=>({definitionKey:String(x?.definitionKey??''),presetKey:String(x?.presetKey??'')}));
    if(selections.some(x=>!key(x.definitionKey)||!key(x.presetKey))||new Set(selections.map(x=>`${x.definitionKey}/${x.presetKey}`)).size!==selections.length)throw new HttpError(400,'Report selections are invalid or duplicated.');
    const fingerprint=createHash('sha256').update(JSON.stringify({batchId:value.batchId,selections})).digest('hex'); const c=await this.pool.connect();
    try{await c.query('begin');
      const samples=await c.query<{id:string;content_type:string;upload_state:string;system_snapshot:unknown}>(`select id,content_type,upload_state,system_snapshot from samples where owner_id=$1 and upload_batch_id=$2 order by created_at,id for share`,[ownerId,value.batchId]);
      if(!samples.rowCount||samples.rows.some(x=>x.upload_state!=='uploaded'||!WAV_TYPES.has(x.content_type.toLowerCase())))throw new HttpError(409,'All report inputs must be verified uploaded WAV files.');
      const snapshot=samples.rows[0].system_snapshot;if(!snapshot||typeof snapshot!=='object'||Array.isArray(snapshot))throw new HttpError(409,'Report inputs require an immutable system snapshot.');
      const defs=await c.query<DefinitionRow>(`select d.id,d.key,d.display_name,d.algorithm_version,p.id preset_id,p.key preset_key,p.display_name preset_name,p.version preset_version,p.snapshot from report_definitions d join report_presets p on p.definition_id=d.id where d.enabled and p.enabled and (d.key,p.key) in (${selections.map((_,i)=>`($${i*2+1},$${i*2+2})`).join(',')})`,selections.flatMap(x=>[x.definitionKey,x.presetKey]));
      if(defs.rowCount!==selections.length)throw new HttpError(409,'A selected report definition or preset is unavailable.');
      const candidateId=randomUUID();const claimed=await c.query<{id:string}>(`insert into report_requests(id,owner_id,upload_batch_id,idempotency_key,request_fingerprint,system_snapshot,user_metadata_snapshot) values($1,$2,$3,$4,$5,$6::jsonb,'{}'::jsonb) on conflict(owner_id,idempotency_key) do nothing returning id`,[candidateId,ownerId,value.batchId,value.idempotencyKey,fingerprint,JSON.stringify(snapshot)]);
      if(!claimed.rowCount){const existing=await c.query<{id:string;request_fingerprint:string}>(`select id,request_fingerprint from report_requests where owner_id=$1 and idempotency_key=$2`,[ownerId,value.idempotencyKey]);if(!existing.rowCount)throw new Error('Report request claim was not visible after conflict.');if(existing.rows[0].request_fingerprint!==fingerprint)throw new HttpError(409,'Idempotency key was already used for a different report request.');await c.query('commit');return{requestId:existing.rows[0].id,reports:(await this.history(ownerId,{requestId:existing.rows[0].id})).items};}
      const requestId=claimed.rows[0]!.id;
      for(const selected of selections){const d=defs.rows.find(x=>x.key===selected.definitionKey&&x.preset_key===selected.presetKey)!;const reportId=randomUUID();const provenance={presetSnapshot:d.snapshot,fixedDemoValues:(d.snapshot as any).fixedDemoAcquisition??{},systemSnapshot:snapshot,userMetadataSnapshot:{},userEnteredValues:{}};await c.query(`insert into analysis_reports(id,request_id,definition_id,preset_id,algorithm_version,status,parameter_provenance) values($1,$2,$3,$4,$5,'queued',$6::jsonb)`,[reportId,requestId,d.id,d.preset_id,d.algorithm_version,JSON.stringify(provenance)]);for(let i=0;i<samples.rows.length;i++)await c.query(`insert into analysis_report_inputs(report_id,sample_id,input_ordinal) values($1,$2,$3)`,[reportId,samples.rows[i].id,i]);}
      await c.query(`insert into report_outbox(id,report_request_id,event_type) values($1,$2,'report.requested')`,[randomUUID(),requestId]);await c.query('commit');return{requestId,reports:(await this.history(ownerId,{requestId})).items};
    }catch(e){await c.query('rollback');throw e}finally{c.release()}
  }
  async history(ownerId:string,filter:{requestId?:string;limit?:number;cursor?:string}={}):Promise<ReportHistoryPage>{const limit=validatedLimit(filter.limit);const cursor=filter.cursor===undefined?undefined:decodeReportCursor(filter.cursor);const r=await this.pool.query<any>(`select ar.id,ar.request_id,d.display_name,d.algorithm_version,p.display_name preset_name,p.version preset_version,ar.status,ar.created_at,ar.completed_at,rr.system_snapshot,coalesce(json_agg(json_build_object('kind',a.kind,'content_type',a.content_type,'created_at',a.created_at)) filter(where a.id is not null),'[]') artifacts from analysis_reports ar join report_requests rr on rr.id=ar.request_id join report_definitions d on d.id=ar.definition_id join report_presets p on p.id=ar.preset_id left join report_artifacts a on a.report_id=ar.id where rr.owner_id=$1 and ($2::uuid is null or ar.request_id=$2) and ($3::timestamptz is null or (ar.created_at,ar.id)<($3::timestamptz,$4::uuid)) group by ar.id,rr.system_snapshot,d.display_name,d.algorithm_version,p.display_name,p.version order by ar.created_at desc,ar.id desc limit $5`,[ownerId,filter.requestId??null,cursor?.createdAt??null,cursor?.id??null,limit+1]);const rows=r.rows.slice(0,limit);const items=rows.map(x=>({id:x.id,requestId:x.request_id,reportType:x.display_name,algorithmVersion:x.algorithm_version,presetName:x.preset_name,presetVersion:x.preset_version,status:x.status,createdAt:x.created_at.toISOString(),completedAt:x.completed_at?.toISOString(),systemName:String(x.system_snapshot?.name??'Unknown system'),artifacts:x.artifacts.map((a:any)=>({kind:a.kind,contentType:a.content_type,createdAt:new Date(a.created_at).toISOString()}))}));const last=rows.at(-1);return{items,limit,...(r.rows.length>limit&&last?{nextCursor:encodeReportCursor({createdAt:last.created_at.toISOString(),id:last.id})}:{})};}
  async artifact(ownerId:string,reportId:string,kind:string){const r=await this.pool.query<{object_key:string;object_version_id:string|undefined}>(`select a.object_key,a.object_version_id from report_artifacts a join analysis_reports ar on ar.id=a.report_id join report_requests rr on rr.id=ar.request_id where a.report_id=$1 and a.kind=$2 and ar.status='completed' and rr.owner_id=$3`,[reportId,kind,ownerId]);return r.rows[0];}
}
export type ClaimedReportRequest={outboxId:string;requestId:string;executionName:string;reportIds:string[]};
/** Transactional outbox claims are leased. A duplicate Step Functions start uses the stable request ID name. */
export class PostgresReportOutbox {
  constructor(private readonly pool:Pool){}
  async claim(limit=10):Promise<ClaimedReportRequest[]>{
    const token=randomUUID(); const c=await this.pool.connect(); try{await c.query('begin');
      const rows=await c.query<{id:string;report_request_id:string;execution_name:string}>(`with candidates as (select id from report_outbox where processed_at is null and available_at<=now() and (claimed_at is null or claimed_at<now()-interval '10 minutes') order by available_at,id for update skip locked limit $1) update report_outbox o set claim_token=$2,claimed_at=now(),attempts=o.attempts+1,execution_name=coalesce(o.execution_name,'report-'||o.report_request_id::text) from candidates c where o.id=c.id returning o.id,o.report_request_id,o.execution_name`,[limit,token]);
      const claimed:ClaimedReportRequest[]=[]; for(const row of rows.rows){const reports=await c.query<{id:string}>(`select id from analysis_reports where request_id=$1 order by created_at,id`,[row.report_request_id]);claimed.push({outboxId:row.id,requestId:row.report_request_id,executionName:row.execution_name,reportIds:reports.rows.map(x=>x.id)});}
      await c.query('commit');return claimed;
    }catch(e){await c.query('rollback');throw e}finally{c.release()}
  }
  async started(item:ClaimedReportRequest,executionArn:string){await this.pool.query(`update report_outbox set processed_at=now(),execution_arn=$3,claim_token=null,claimed_at=null,last_error_safe=null where id=$1 and report_request_id=$2`,[item.outboxId,item.requestId,executionArn]);await this.pool.query(`update report_requests set status='running' where id=$1 and status='queued'`,[item.requestId]);}
  async retry(item:ClaimedReportRequest,error:unknown){const message=error instanceof Error?error.message.slice(0,500):'Workflow start failed.';await this.pool.query(`update report_outbox set claim_token=null,claimed_at=null,available_at=now()+interval '1 minute',last_error_safe=$2 where id=$1 and report_request_id=$3 and processed_at is null`,[item.outboxId,message,item.requestId]);}
  /** Scheduled recovery closes requests whose Map children are terminal after a finalizer outage. */
  async recoverTerminalRequests(){await this.pool.query(`update report_requests rr set status=case when exists(select 1 from analysis_reports ar where ar.request_id=rr.id and ar.status='failed') and exists(select 1 from analysis_reports ar where ar.request_id=rr.id and ar.status='completed') then 'partial_failed' when exists(select 1 from analysis_reports ar where ar.request_id=rr.id and ar.status='failed') then 'failed' else 'completed' end where rr.status='running' and not exists(select 1 from analysis_reports ar where ar.request_id=rr.id and ar.status in ('queued','running'))`);}
}
export interface ReportExecutionStarter { start(input:{requestId:string;reportIds:string[];executionName:string}):Promise<{executionArn:string}> }
export async function dispatchReportOutbox(outbox:PostgresReportOutbox,starter:ReportExecutionStarter):Promise<number>{let count=0;for(const item of await outbox.claim()){try{const execution=await starter.start({requestId:item.requestId,reportIds:item.reportIds,executionName:item.executionName});await outbox.started(item,execution.executionArn);count++;}catch(error){await outbox.retry(item,error);}}await outbox.recoverTerminalRequests();return count;}
function validatedLimit(value:number|undefined){const limit=value??25;if(!Number.isInteger(limit)||limit<1||limit>100)throw new HttpError(400,'limit must be an integer from 1 to 100.');return limit;}
function key(x:string){return/^[a-z0-9-]{1,80}$/.test(x)} function uuid(x:string){return/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x)}
