import { createHash, randomUUID } from 'node:crypto';
import type { CreateSampleUploadBatchRequest, SampleSummary } from '@wally/contracts';
import { Pool } from 'pg';
import { HttpError } from './auth.js';
import { newObjectKey, type UploadIntentRow } from './sampleUploads.js';

type SampleRow={id:string;upload_batch_id:string;psiu_unit_id:string;object_key:string;content_type:string;byte_length:number;checksum_sha256:string|null;recorded_at:Date;upload_state:'intent'|'uploaded'|'failed';metadata:Record<string,unknown>;created_at:Date;uploaded_at:Date|null};
export interface SampleRepository { createBatch(ownerId:string, request:CreateSampleUploadBatchRequest):Promise<{batchId:string;intents:UploadIntentRow[]}>; intent(ownerId:string,sampleId:string):Promise<UploadIntentRow|undefined>; objectKey(ownerId:string,sampleId:string):Promise<string|undefined>; complete(ownerId:string,sampleId:string,metadata:{sampleRateHz:number;channels:number;bitsPerSample:number;durationMs:number}):Promise<SampleSummary>; list(ownerId:string):Promise<SampleSummary[]>; sample(ownerId:string,sampleId:string):Promise<SampleSummary|undefined>; }
export class PostgresSampleRepository implements SampleRepository {
  constructor(private readonly pool:Pool) {}
  async createBatch(ownerId:string, request:CreateSampleUploadBatchRequest){const c=await this.pool.connect();try{await c.query('begin');const assigned=await c.query<{serial_number:string;opaque_uid:string}>(`select p.serial_number,p.opaque_uid from psiu_units p join psiu_assignments a on a.psiu_unit_id=p.id and a.unassigned_at is null where p.id=$1 and p.status='enabled' and a.user_id=$2 for share`,[request.psiuUnitId,ownerId]);if(!assigned.rowCount)throw new HttpError(403,'An assigned enabled PSIU unit is required.');const fingerprint=requestFingerprint(request);const existing=await c.query<{id:string;request_fingerprint:string}>(`select id,request_fingerprint from sample_upload_batches where owner_id=$1 and idempotency_key=$2`,[ownerId,request.idempotencyKey]);if(existing.rowCount&&existing.rows[0].request_fingerprint!==fingerprint)throw new HttpError(409,'Upload idempotency key was already used for different files.');const batchId=existing.rows[0]?.id??randomUUID();if(!existing.rowCount)await c.query(`insert into sample_upload_batches(id,owner_id,psiu_unit_id,idempotency_key,request_fingerprint) values($1,$2,$3,$4,$5)`,[batchId,ownerId,request.psiuUnitId,request.idempotencyKey,fingerprint]);let rows:SampleRow[];if(existing.rowCount)rows=(await c.query<SampleRow>(`select * from samples where owner_id=$1 and upload_batch_id=$2 order by created_at`,[ownerId,batchId])).rows;else { rows=[];for(const file of request.files){const id=randomUUID();const key=newObjectKey(ownerId,id,file.fileName);const metadata={clientFileId:file.clientFileId,fileName:file.fileName,psiuSerialNumber:assigned.rows[0].serial_number,psiuUid:assigned.rows[0].opaque_uid};const row=await c.query<SampleRow>(`insert into samples(id,owner_id,upload_batch_id,psiu_unit_id,object_key,content_type,byte_length,checksum_sha256,recorded_at,status,upload_state,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,'uploaded','intent',$10::jsonb) returning *`,[id,ownerId,batchId,request.psiuUnitId,key,file.contentType,file.byteLength,file.sha256Base64??null,file.recordedAt,JSON.stringify(metadata)]);rows.push(row.rows[0]);}}await c.query('commit');return{batchId,intents:rows.map(intent)};}catch(e){await c.query('rollback');throw e;}finally{c.release();}}
  async intent(ownerId:string,sampleId:string){const r=await this.pool.query<SampleRow>(`select * from samples where id=$1 and owner_id=$2 and upload_state='intent'`,[sampleId,ownerId]);return r.rowCount?intent(r.rows[0]):undefined;}
  async objectKey(ownerId:string,sampleId:string){const r=await this.pool.query<{object_key:string}>(`select object_key from samples where id=$1 and owner_id=$2 and upload_state='uploaded'`,[sampleId,ownerId]);return r.rows[0]?.object_key;}
  async complete(ownerId:string,sampleId:string,metadata:{sampleRateHz:number;channels:number;bitsPerSample:number;durationMs:number}){const r=await this.pool.query<SampleRow>(`update samples set upload_state='uploaded',uploaded_at=coalesce(uploaded_at,now()),verified_at=now(),metadata=metadata || $3::jsonb where id=$1 and owner_id=$2 and upload_state in ('intent','uploaded') returning *`,[sampleId,ownerId,JSON.stringify(metadata)]);if(!r.rowCount)throw new HttpError(404,'Upload intent not found.');return summary(r.rows[0]);}
  async list(ownerId:string){const r=await this.pool.query<SampleRow>(`select * from samples where owner_id=$1 order by created_at desc`,[ownerId]);return r.rows.map(summary);}
  async sample(ownerId:string,sampleId:string){const r=await this.pool.query<SampleRow>(`select * from samples where id=$1 and owner_id=$2 and upload_state='uploaded'`,[sampleId,ownerId]);return r.rowCount?summary(r.rows[0]):undefined;}
}
function intent(row:SampleRow):UploadIntentRow{return{sampleId:row.id,clientFileId:String(row.metadata.clientFileId),fileName:String(row.metadata.fileName),objectKey:row.object_key,contentType:row.content_type,byteLength:Number(row.byte_length),sha256Base64:row.checksum_sha256??undefined};}
function summary(row:SampleRow):SampleSummary{return{id:row.id,batchId:row.upload_batch_id,psiuUnitId:row.psiu_unit_id,fileName:String(row.metadata.fileName),contentType:row.content_type,byteLength:Number(row.byte_length),sha256Base64:row.checksum_sha256??undefined,recordedAt:row.recorded_at.toISOString(),uploadState:row.upload_state,sampleRateHz:number(row.metadata.sampleRateHz),channels:number(row.metadata.channels),bitsPerSample:number(row.metadata.bitsPerSample),durationMs:number(row.metadata.durationMs),createdAt:row.created_at.toISOString(),uploadedAt:row.uploaded_at?.toISOString()};}
function number(v:unknown){return typeof v==='number'?v:undefined;}
function requestFingerprint(request:CreateSampleUploadBatchRequest):string{return createHash('sha256').update(JSON.stringify({psiuUnitId:request.psiuUnitId,files:request.files.map(file=>({clientFileId:file.clientFileId,fileName:file.fileName,contentType:file.contentType,byteLength:file.byteLength,sha256Base64:file.sha256Base64??null,recordedAt:file.recordedAt}))})).digest('hex');}
