import { randomUUID } from 'node:crypto';
import type { UserAlert } from '@wally/contracts';
import { Pool } from 'pg';
import { HttpError } from './auth.js';
type Row={id:string;event_key:string;severity:UserAlert['severity'];title:string;message:string;action_label:string|null;action_route:string|null;dismissible:boolean;created_at:Date};
export class PostgresUserAlertsRepository { constructor(private readonly pool:Pool) {}
  async refresh(ownerId:string){const c=await this.pool.connect();try{await c.query('begin');const systems=await c.query(`select exists(select 1 from user_systems where owner_id=$1 and active and retired_at is null) ok`,[ownerId]);const credits=await c.query<{balance:number}>(`select coalesce((select balance_after from credit_ledger_entries where owner_id=$1 order by created_at desc,id desc limit 1),0) balance`,[ownerId]);await this.sync(c,ownerId,'system_required',!systems.rows[0].ok,{severity:'warning',title:'Create a recording system',message:'Create an active system before capturing samples.',actionLabel:'Create system',actionRoute:'/systems'});await this.sync(c,ownerId,'credits_low',credits.rows[0].balance<=2,{severity:'warning',title:'Credits are low',message:'Your credit balance is 2 or below.',actionLabel:'View credits',actionRoute:'/credits'});await c.query('commit');}catch(e){await c.query('rollback');throw e}finally{c.release()}}
  private async sync(c:any,owner:string,key:string,open:boolean,v:{severity:UserAlert['severity'];title:string;message:string;actionLabel:string;actionRoute:string}){if(open)await c.query(`insert into user_alerts(id,owner_id,event_key,severity,title,message,action_label,action_route,status) values($1,$2,$3,$4,$5,$6,$7,$8,'open') on conflict(owner_id,event_key) do update set status='open',dismissed_at=null,resolved_at=null,severity=excluded.severity,title=excluded.title,message=excluded.message,action_label=excluded.action_label,action_route=excluded.action_route where user_alerts.status='resolved'`,[randomUUID(),owner,key,v.severity,v.title,v.message,v.actionLabel,v.actionRoute]);else await c.query(`update user_alerts set status='resolved',resolved_at=now() where owner_id=$1 and event_key=$2 and status='open'`,[owner,key]);}
  async list(owner:string):Promise<UserAlert[]>{await this.refresh(owner);const r=await this.pool.query<Row>(`select id,event_key,severity,title,message,action_label,action_route,dismissible,created_at from user_alerts where owner_id=$1 and status='open' order by created_at desc`,[owner]);return r.rows.map(x=>({id:x.id,eventKey:x.event_key,severity:x.severity,title:x.title,message:x.message,actionLabel:x.action_label??undefined,actionRoute:x.action_route??undefined,dismissible:x.dismissible,createdAt:x.created_at.toISOString()}));}
  async dismiss(owner:string,id:string){const r=await this.pool.query(`update user_alerts set status='dismissed',dismissed_at=now() where id=$1 and owner_id=$2 and status='open' and dismissible`,[id,owner]);if(!r.rowCount)throw new HttpError(404,'Open alert not found.');}
}
