import { randomUUID } from 'node:crypto';
import type { CreditLedgerEntry, CreditsResponse, CreateSystemRequest, MeResponse, UpdateProfileRequest, UserSystem } from '@wally/contracts';
import { Pool } from 'pg';
import { HttpError } from './auth.js';

type SystemRow={id:string;name:string;notes:string;components:{turntable:string;tonearm:string;cartridge:string;headshell?:string};active:boolean;created_at:Date};
type CreditRow={id:string;kind:CreditLedgerEntry['kind'];delta:number;balance_after:number;note:string;created_at:Date};
export class PostgresUserExperienceRepository {
  constructor(private readonly pool:Pool){}
  async updateProfile(ownerId:string,value:UpdateProfileRequest):Promise<Pick<MeResponse,'firstName'|'lastName'>>{const firstName=clean(value.firstName,'First name',100),lastName=clean(value.lastName,'Last name',100);const r=await this.pool.query<{first_name:string;last_name:string}>(`update users set first_name=$2,last_name=$3,updated_at=now() where id=$1 returning first_name,last_name`,[ownerId,firstName,lastName]);if(!r.rowCount)throw new HttpError(404,'Account not found.');return{firstName:r.rows[0].first_name,lastName:r.rows[0].last_name};}
  async systems(ownerId:string):Promise<UserSystem[]>{const r=await this.pool.query<SystemRow>(`select id,name,notes,components,active,created_at from user_systems where owner_id=$1 and retired_at is null order by active desc,created_at desc`,[ownerId]);return r.rows.map(system);}
  async createSystem(ownerId:string,value:CreateSystemRequest):Promise<UserSystem>{const x=normalizeSystem(value);const c=await this.pool.connect();try{await c.query('begin');if(x.active)await c.query(`update user_systems set active=false,updated_at=now() where owner_id=$1 and active and retired_at is null`,[ownerId]);const r=await c.query<SystemRow>(`insert into user_systems(id,owner_id,name,notes,components,active) values($1,$2,$3,$4,$5::jsonb,$6) returning id,name,notes,components,active,created_at`,[randomUUID(),ownerId,x.name,x.notes,JSON.stringify(x.components),x.active]);await c.query('commit');return system(r.rows[0]);}catch(e){await c.query('rollback');throw e;}finally{c.release();}}
  async setActive(ownerId:string,id:string):Promise<void>{const c=await this.pool.connect();try{await c.query('begin');const r=await c.query(`select id from user_systems where id=$1 and owner_id=$2 and retired_at is null for update`,[id,ownerId]);if(!r.rowCount)throw new HttpError(404,'System not found.');await c.query(`update user_systems set active=false,updated_at=now() where owner_id=$1 and active and retired_at is null`,[ownerId]);await c.query(`update user_systems set active=true,updated_at=now() where id=$1`,[id]);await c.query('commit');}catch(e){await c.query('rollback');throw e;}finally{c.release();}}
  async credits(ownerId:string):Promise<CreditsResponse>{const r=await this.pool.query<CreditRow>(`select id,kind,delta,balance_after,note,created_at from credit_ledger_entries where owner_id=$1 order by created_at desc`,[ownerId]);return{balance:r.rows[0]?.balance_after??0,entries:r.rows.map(x=>({id:x.id,kind:x.kind,delta:x.delta,balanceAfter:x.balance_after,note:x.note,createdAt:x.created_at.toISOString()}))};}
}
function clean(v:string,label:string,max:number){const x=v?.trim();if(!x||x.length>max||/[\u0000-\u001f]/.test(x))throw new HttpError(400,`${label} is invalid.`);return x;}
function normalizeSystem(v:CreateSystemRequest){return{name:clean(v.name,'System name',160),notes:(v.notes??'').trim(),active:v.active!==false,components:{turntable:clean(v.components?.turntable,'Turntable',160),tonearm:clean(v.components?.tonearm,'Tonearm',160),cartridge:clean(v.components?.cartridge,'Cartridge',160),...(v.components?.headshell?.trim()?{headshell:clean(v.components.headshell,'Headshell',160)}:{})}};}
function system(x:SystemRow):UserSystem{return{id:x.id,name:x.name,notes:x.notes,components:x.components,active:x.active,createdAt:x.created_at.toISOString()};}
