import { randomUUID } from 'node:crypto';
import type { CreditLedgerEntry, CreditsResponse, CreateSystemRequest, MeResponse, UpdateProfileRequest, UpdateSystemRequest, UserSystem } from '@wally/contracts';
import { Pool } from 'pg';
import { HttpError } from './auth.js';
import { normalizeProfile } from './adminDataRepository.js';

type SystemRow={id:string;name:string;notes:string;components:{turntable:string;tonearm:string;cartridge:string;headshell?:string};active:boolean;created_at:Date};
type CreditRow={id:string;kind:CreditLedgerEntry['kind'];delta:number;balance_after:number;note:string;created_at:Date};
export class PostgresUserExperienceRepository {
  constructor(private readonly pool:Pool){}
  async updateProfile(ownerId:string,value:UpdateProfileRequest):Promise<Pick<MeResponse,'firstName'|'lastName'|'address'>>{const profile=normalizeProfile(value);const r=await this.pool.query<{first_name:string|null;last_name:string|null;address_line1:string|null;address_line2:string|null;address_city:string|null;address_region:string|null;address_postal_code:string|null;address_country_code:string|null}>(`update users set first_name=case when $2 then $3 else first_name end,last_name=case when $4 then $5 else last_name end,address_line1=case when $6 then $7 else address_line1 end,address_line2=case when $8 then $9 else address_line2 end,address_city=case when $10 then $11 else address_city end,address_region=case when $12 then $13 else address_region end,address_postal_code=case when $14 then $15 else address_postal_code end,address_country_code=case when $16 then $17 else address_country_code end,updated_at=now() where id=$1 returning first_name,last_name,address_line1,address_line2,address_city,address_region,address_postal_code,address_country_code`,[ownerId,profile.present.firstName,profile.firstName,profile.present.lastName,profile.lastName,profile.present.address.line1,profile.address.line1,profile.present.address.line2,profile.address.line2,profile.present.address.city,profile.address.city,profile.present.address.region,profile.address.region,profile.present.address.postalCode,profile.address.postalCode,profile.present.address.countryCode,profile.address.countryCode]);if(!r.rowCount)throw new HttpError(404,'Account not found.');const x=r.rows[0];const address=x.address_line1&&x.address_city&&x.address_region&&x.address_postal_code&&x.address_country_code?{line1:x.address_line1,line2:x.address_line2??undefined,city:x.address_city,region:x.address_region,postalCode:x.address_postal_code,countryCode:x.address_country_code}:undefined;return{firstName:x.first_name??undefined,lastName:x.last_name??undefined,address};}
  async systems(ownerId:string):Promise<UserSystem[]>{const r=await this.pool.query<SystemRow>(`select id,name,notes,components,active,created_at from user_systems where owner_id=$1 and retired_at is null order by active desc,created_at desc`,[ownerId]);return r.rows.map(system);}
  async createSystem(ownerId:string,value:CreateSystemRequest):Promise<UserSystem>{const x=normalizeSystem(value);const c=await this.pool.connect();try{await c.query('begin');if(x.active)await c.query(`update user_systems set active=false,updated_at=now() where owner_id=$1 and active and retired_at is null`,[ownerId]);const r=await c.query<SystemRow>(`insert into user_systems(id,owner_id,name,notes,components,active) values($1,$2,$3,$4,$5::jsonb,$6) returning id,name,notes,components,active,created_at`,[randomUUID(),ownerId,x.name,x.notes,JSON.stringify(x.components),x.active]);await c.query('commit');return system(r.rows[0]);}catch(e){await c.query('rollback');throw e;}finally{c.release();}}
  async updateSystem(ownerId:string,id:string,value:UpdateSystemRequest):Promise<UserSystem>{const x=normalizeSystem(value);const r=await this.pool.query<SystemRow>(`update user_systems set name=$3,notes=$4,components=$5::jsonb,updated_at=now() where id=$1 and owner_id=$2 and retired_at is null returning id,name,notes,components,active,created_at`,[id,ownerId,x.name,x.notes,JSON.stringify(x.components)]);if(!r.rowCount)throw new HttpError(404,'System not found.');return system(r.rows[0]);}
  async setActive(ownerId:string,id:string):Promise<void>{const c=await this.pool.connect();try{await c.query('begin');const r=await c.query(`select id from user_systems where id=$1 and owner_id=$2 and retired_at is null for update`,[id,ownerId]);if(!r.rowCount)throw new HttpError(404,'System not found.');await c.query(`update user_systems set active=false,updated_at=now() where owner_id=$1 and active and retired_at is null`,[ownerId]);await c.query(`update user_systems set active=true,updated_at=now() where id=$1 and owner_id=$2`,[id,ownerId]);await c.query('commit');}catch(e){await c.query('rollback');throw e;}finally{c.release();}}
  async credits(ownerId:string):Promise<CreditsResponse>{const r=await this.pool.query<CreditRow>(`select id,kind,delta,balance_after,note,created_at from credit_ledger_entries where owner_id=$1 order by created_at desc`,[ownerId]);return{balance:r.rows[0]?.balance_after??0,items:r.rows.map(x=>({id:x.id,kind:x.kind,delta:x.delta,balance_after:x.balance_after,note:x.note,created_at:x.created_at.toISOString()})),limit:r.rowCount??0,offset:0};}
}
function clean(v:string,label:string,max:number){const x=v?.trim();if(!x||x.length>max||/[\u0000-\u001f]/.test(x))throw new HttpError(400,`${label} is invalid.`);return x;}
function normalizeSystem(v:CreateSystemRequest){return{name:clean(v.name,'System name',160),notes:(v.notes??'').trim(),active:v.active!==false,components:{turntable:clean(v.components?.turntable,'Turntable',160),tonearm:clean(v.components?.tonearm,'Tonearm',160),cartridge:clean(v.components?.cartridge,'Cartridge',160),...(v.components?.headshell?.trim()?{headshell:clean(v.components.headshell,'Headshell',160)}:{})}};}
function system(x:SystemRow):UserSystem{return{id:x.id,name:x.name,notes:x.notes,components:x.components,active:x.active,createdAt:x.created_at.toISOString()};}
