import { randomUUID } from 'node:crypto';
import { HeadObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { StartExecutionCommand, SFNClient } from '@aws-sdk/client-sfn';
import { Pool } from 'pg';
import { databaseSettings } from '../migrate.js';
import { PostgresReportOutbox, dispatchReportOutbox } from '../services/reportRepository.js';

const rawBucket=required('SAMPLE_BUCKET_NAME'), reportBucket=required('REPORT_BUCKET_NAME');
const s3=new S3Client({});
let pool:Pool|undefined;
async function db(){return pool??=new Pool(await databaseSettings());}

type WorkflowInput={requestId:string;reportId:string};
/** Scheduler target: claims committed outbox rows and starts a stable, idempotent execution name. */
export async function dispatch(){
  const machine=required('REPORT_STATE_MACHINE_ARN'); const sfn=new SFNClient({});
  const started=await dispatchReportOutbox(new PostgresReportOutbox(await db()),{start:async x=>{
    try { const r=await sfn.send(new StartExecutionCommand({stateMachineArn:machine,name:x.executionName,input:JSON.stringify({requestId:x.requestId,reportIds:x.reportIds})})); return {executionArn:r.executionArn!}; }
    catch(error) { if(typeof error==='object'&&error&&'name' in error&&(error as {name?:string}).name==='ExecutionAlreadyExists') return {executionArn:`existing:${x.executionName}`}; throw error; }
  }});
  return {started};
}
/** Re-reads immutable database inputs and S3 object versions before an untrusted worker runs. */
export async function preflight(event:WorkflowInput){const p=await db();const r=await p.query<any>(`select ar.id,rr.id request_id,rr.owner_id,rr.system_snapshot,ar.algorithm_version,ar.parameter_provenance, s.id sample_id,s.object_key,s.checksum_sha256,s.content_type from analysis_reports ar join report_requests rr on rr.id=ar.request_id join analysis_report_inputs i on i.report_id=ar.id join samples s on s.id=i.sample_id where ar.id=$1 and rr.id=$2 and ar.status in ('queued','running') and s.upload_state='uploaded' order by i.input_ordinal`,[event.reportId,event.requestId]);if(!r.rowCount)throw new Error('Report inputs are unavailable.');const first=r.rows[0];const inputs=[];for(const row of r.rows){const head=await s3.send(new HeadObjectCommand({Bucket:rawBucket,Key:row.object_key}));if(!head.VersionId||!head.ETag)throw new Error('Raw input has no immutable object version.');inputs.push({sampleId:row.sample_id,objectKey:row.object_key,versionId:head.VersionId,etag:String(head.ETag).replaceAll('"',''),checksumSha256:row.checksum_sha256??undefined,contentType:row.content_type});}await p.query(`update analysis_reports set status='running',started_at=coalesce(started_at,now()) where id=$1 and status='queued'`,[event.reportId]);return{requestId:event.requestId,reportId:event.reportId,ownerId:first.owner_id,algorithmVersion:first.algorithm_version,systemSnapshot:first.system_snapshot,parameterProvenance:first.parameter_provenance,inputs,reportPrefix:`reports/${first.owner_id}/${event.reportId}/`};}
/** Never accepts arbitrary object paths: head/checksum/prefix checks precede persistence. */
export type WorkerArtifact={kind:string;objectKey:string;contentType:string;byteLength:number;checksumSha256:string};
export function artifactDescriptorIsValid(artifact:WorkerArtifact,prefix:string){const allowed=new Map([['manifest','application/json'],['metrics_json','application/json'],['graph_svg','image/svg+xml'],['report_pdf','application/pdf']]);return (allowed.has(artifact.kind)||/^graph_svg_[1-9][0-9]*$/.test(artifact.kind))&&(allowed.get(artifact.kind)??'image/svg+xml')===artifact.contentType&&artifact.objectKey.startsWith(prefix)&&artifact.checksumSha256?.match(/^[a-f0-9]{64}$/)!==null&&Number.isSafeInteger(artifact.byteLength)&&artifact.byteLength>=0;}
export async function finalize(event:{reportId:string;ownerId:string;reportPrefix:string;artifacts:WorkerArtifact[]}){if(!Array.isArray(event.artifacts)||!event.artifacts.length)throw new Error('Worker returned no artifacts.');const p=await db();for(const artifact of event.artifacts){if(!artifactDescriptorIsValid(artifact,event.reportPrefix))throw new Error('Invalid report artifact descriptor.');const head=await s3.send(new HeadObjectCommand({Bucket:reportBucket,Key:artifact.objectKey}));if(head.ContentLength!==artifact.byteLength||head.Metadata?.sha256!==artifact.checksumSha256)throw new Error('Report artifact integrity validation failed.');}const c=await p.connect();try{await c.query('begin');const owned=await c.query(`select ar.id from analysis_reports ar join report_requests rr on rr.id=ar.request_id where ar.id=$1 and rr.owner_id=$2 for update`,[event.reportId,event.ownerId]);if(!owned.rowCount)throw new Error('Report ownership mismatch.');for(const a of event.artifacts)await c.query(`insert into report_artifacts(id,report_id,kind,object_key,content_type,byte_length,checksum_sha256) values($1,$2,$3,$4,$5,$6,$7) on conflict(report_id,kind) do update set object_key=excluded.object_key,content_type=excluded.content_type,byte_length=excluded.byte_length,checksum_sha256=excluded.checksum_sha256`,[randomUUID(),event.reportId,a.kind,a.objectKey,a.contentType,a.byteLength,a.checksumSha256]);await c.query(`update analysis_reports set status='completed',completed_at=now(),failure_code=null,failure_detail_safe=null where id=$1`,[event.reportId]);await c.query('commit');return{reportId:event.reportId,status:'completed'};}catch(e){await c.query('rollback');throw e;}finally{c.release()}}
export async function fail(event:{reportId:string;error?:string}){const p=await db();await p.query(`update analysis_reports set status='failed',completed_at=now(),failure_code='processing_failed',failure_detail_safe=$2 where id=$1 and status in ('queued','running')`,[event.reportId,String(event.error??'Report processing failed.').slice(0,500)]);return{reportId:event.reportId,status:'failed'};}
export async function finalizeRequest(event:{requestId:string}){const p=await db();const r=await p.query<{status:string;count:string}>(`select status,count(*) from analysis_reports where request_id=$1 group by status`,[event.requestId]);const counts=Object.fromEntries(r.rows.map(x=>[x.status,Number(x.count)]));const status=counts.failed&&counts.completed?'partial_failed':counts.failed?'failed':counts.completed?'completed':'running';await p.query(`update report_requests set status=$2 where id=$1`,[event.requestId,status]);return{requestId:event.requestId,status,counts};}
function required(name:string){const value=process.env[name];if(!value)throw new Error(`Missing ${name}`);return value;}
