import { AuthenticationDetails, CognitoUser, CognitoUserPool, type CognitoUserSession } from 'amazon-cognito-identity-js';
const poolId=import.meta.env.VITE_COGNITO_USER_POOL_ID as string|undefined;
const clientId=import.meta.env.VITE_COGNITO_WEB_CLIENT_ID as string|undefined;
const pool=poolId&&clientId?new CognitoUserPool({UserPoolId:poolId,ClientId:clientId}):undefined;
export function configured(){return Boolean(pool)}
export async function accessToken():Promise<string>{const user=pool?.getCurrentUser();if(!user)throw Error('Sign in required.');return new Promise((resolve,reject)=>user.getSession((error: Error|null,session: CognitoUserSession)=>error?reject(error):resolve(session.getAccessToken().getJwtToken())))}
export async function login(email:string,password:string){if(!pool)throw Error('Cognito configuration required.');const user=new CognitoUser({Username:email,Pool:pool});return new Promise<void>((resolve,reject)=>user.authenticateUser(new AuthenticationDetails({Username:email,Password:password}),{onSuccess:()=>resolve(),onFailure:reject,newPasswordRequired:()=>reject(Error('Temporary password must be changed.'))}))}
export async function completeTemporaryPassword(email:string,temporaryPassword:string,newPassword:string){if(!pool)throw Error('Cognito configuration required.');const user=new CognitoUser({Username:email,Pool:pool});return new Promise<void>((resolve,reject)=>user.authenticateUser(new AuthenticationDetails({Username:email,Password:temporaryPassword}),{onSuccess:()=>resolve(),onFailure:reject,newPasswordRequired:()=>user.completeNewPasswordChallenge(newPassword,{}, {onSuccess:()=>resolve(),onFailure:reject})}))}
export function logout(){pool?.getCurrentUser()?.signOut()}
export async function forgotPassword(email:string){if(!pool)throw Error('Cognito configuration required.');const u=new CognitoUser({Username:email,Pool:pool});return new Promise<void>((resolve,reject)=>u.forgotPassword({onSuccess:()=>resolve(),onFailure:reject,inputVerificationCode:()=>resolve()}))}
export async function resetPassword(email:string,code:string,password:string){if(!pool)throw Error('Cognito configuration required.');const u=new CognitoUser({Username:email,Pool:pool});return new Promise<void>((resolve,reject)=>u.confirmPassword(code,password,{onSuccess:()=>resolve(),onFailure:reject}))}
export async function changePassword(oldPassword:string,newPassword:string){if(!pool)throw Error('Cognito configuration required.');const u=pool.getCurrentUser();if(!u)throw Error('Sign in required.');return new Promise<void>((resolve,reject)=>u.getSession((e: Error|null)=>e?reject(e):u.changePassword(oldPassword,newPassword,(x?: Error)=>x?reject(x):resolve()))) }
