import { AuthenticationDetails, CognitoUser, CognitoUserPool, type CognitoUserSession } from 'amazon-cognito-identity-js';
import { cognitoUserPoolId as poolId, cognitoWebClientId as clientId } from './runtimeConfig.js';
const pool=poolId&&clientId?new CognitoUserPool({UserPoolId:poolId,ClientId:clientId}):undefined;
// Credentials must never be entered on the temporary plaintext ALB. Local UI
// verification uses the separate mock API/auth harness, not Cognito browser auth.
export function configured(){return Boolean(pool) && window.location.protocol === 'https:'}
export async function accessToken():Promise<string>{if(!configured())throw Error('HTTPS Cognito configuration required.');const user=pool?.getCurrentUser();if(!user)throw Error('Sign in required.');return new Promise((resolve,reject)=>user.getSession((error: Error|null,session: CognitoUserSession)=>error?reject(error):resolve(session.getAccessToken().getJwtToken())))}
export async function login(email:string,password:string){if(!configured()||!pool)throw Error('HTTPS Cognito configuration required.');const user=new CognitoUser({Username:email,Pool:pool});return new Promise<void>((resolve,reject)=>user.authenticateUser(new AuthenticationDetails({Username:email,Password:password}),{onSuccess:()=>resolve(),onFailure:reject,newPasswordRequired:()=>reject(Error('Temporary password must be changed.'))}))}
export async function completeTemporaryPassword(email:string,temporaryPassword:string,newPassword:string){if(!configured()||!pool)throw Error('HTTPS Cognito configuration required.');const user=new CognitoUser({Username:email,Pool:pool});return new Promise<void>((resolve,reject)=>user.authenticateUser(new AuthenticationDetails({Username:email,Password:temporaryPassword}),{onSuccess:()=>resolve(),onFailure:reject,newPasswordRequired:()=>user.completeNewPasswordChallenge(newPassword,{}, {onSuccess:()=>resolve(),onFailure:reject})}))}
export function logout(){pool?.getCurrentUser()?.signOut()}
export async function forgotPassword(email:string){if(!configured()||!pool)throw Error('HTTPS Cognito configuration required.');const u=new CognitoUser({Username:email,Pool:pool});return new Promise<void>((resolve,reject)=>u.forgotPassword({onSuccess:()=>resolve(),onFailure:reject,inputVerificationCode:()=>resolve()}))}
export async function resetPassword(email:string,code:string,password:string){if(!configured()||!pool)throw Error('HTTPS Cognito configuration required.');const u=new CognitoUser({Username:email,Pool:pool});return new Promise<void>((resolve,reject)=>u.confirmPassword(code,password,{onSuccess:()=>resolve(),onFailure:reject}))}
export async function changePassword(oldPassword:string,newPassword:string){if(!configured()||!pool)throw Error('HTTPS Cognito configuration required.');const u=pool.getCurrentUser();if(!u)throw Error('Sign in required.');return new Promise<void>((resolve,reject)=>u.getSession((e: Error|null)=>e?reject(e):u.changePassword(oldPassword,newPassword,(x?: Error)=>x?reject(x):resolve()))) }
